version: "3"

services:

  database:
    build: "./Database"
    #image: my-mysql
    ports:
      - "3306:3306"
    restart: always
    #command: --default-authentication-pllugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: app123
      MYSQL_DATABASE: catalog1
  app:
    #banco de dados precisa iniciar para o app rodar
    build: "./GiLuFlixBack"
    depends_on:
      - database
    ports:
      - "5041:8080"
    container_name: my-app-container
    restart: always

    environment:
      DBHOST: database
      ASPNETCORE_ENVIRONMENT: Development
      DATABASE_NAME: catalog1
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: app123
  
