// <auto-generated />
using System;
using GiLuFlixBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GiLuFlixBack.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240330125128_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GiLuFlixBack.Models.Filme", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<int?>("ano")
                        .HasColumnType("int")
                        .HasColumnName("ano");

                    b.Property<string>("diretor")
                        .HasColumnType("longtext")
                        .HasColumnName("diretor");

                    b.Property<string>("elencoPrincipal")
                        .HasColumnType("longtext")
                        .HasColumnName("elenco_principal");

                    b.Property<string>("pais")
                        .HasColumnType("longtext")
                        .HasColumnName("pais");

                    b.Property<string>("titulo")
                        .HasColumnType("longtext")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("Filme");
                });
#pragma warning restore 612, 618
        }
    }
}
