name: GitHub Actions App
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

#Qual vai ser o evento de trigger
#voce pode especificar tambem as branchs
on: [push]


#passo a passo para ser executado
jobs:
  #nome do job
  app-build:
    runs-on: ubuntu-latest
    #passos que devem acontecer nesse job
    
    steps:
      - name: Clone our code into the virtual machine
      # Essa action faz um gitclone e faz checkout p uma branch especifica
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            
      - name: Login no Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build Docker
        run: docker-compose build

      - name: Push Docker Images
        run: docker-compose push

  deploy:
    needs: app-build
    runs-on: self-hosted

    steps:

      - name: Pull image from Docker hub 
        run: docker-compose pull 

      - name: Run Docker 
        run: docker-compose build; docker-compose up -d