name: GitHub Actions App
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

#Qual vai ser o evento de trigger
#voce pode especificar tambem as branchs
on: [push]


#passo a passo para ser executado
jobs:
  #nome do job
  continuous-integration:
    runs-on: ubuntu-latest
    #passos que devem acontecer nesse job
    
    steps:
      - name: Clone our code into the virtual machine
      # Essa action faz um gitclone e faz checkout p uma branch especifica
        uses: action/checkout@v3
      
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        #with serve para passar parametros a uma action
        with: 
          #deve ser passado no formato ${{ secrets.DOCKERHUB_USERNAME }} 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: Lucas10sh/giluflixapp

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true         
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


